version: "3.5"

services:
  rabbit_mq:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672   #amqp protocol // http,https,ftp,ssh  >>access queue<<
      - 15672:15672  #http for monitoring queue
